x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

services:

  rviz:
    image: husarion/rviz2:humble-11.2.6-20230809
    <<: *gpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz

  rosbot-xl:
    image: husarion/rosbot-xl-gazebo:humble-0.8.2-20230712
    <<: *gpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 launch rosbot_xl_gazebo simulation.launch.py mecanum:=${MECANUM:-True}

  navigation:
    image: husarion/navigation2:humble-arm64-from-sourece
    <<: *gpu-config
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    command: >
      ros2 launch nav2_bringup bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=True
