x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: unless-stopped

x-dds-envs:
  &dds-envs
  env_file: .env.dds

services:

  ros2router:
    image: husarnet/ros2router:1.9.0
    <<: *common-config
    environment:
      - USER
      - PARTICIPANTS=husarnet,shm

  rviz:
    image: husarion/rviz2:humble-11.2.9-20240111
    runtime: ${DOCKER_RUNTIME:-runc}
    <<:
      - *common-config
      - *dds-envs
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
      - NVIDIA_VISIBLE_DEVICES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
      - NVIDIA_DRIVER_CAPABILITIES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
    command: >
      rviz2 -d /default.rviz --ros-args
        -r /tf:=tf
        -r /tf_static:=tf_static
        -r __ns:=/${ROBOT_NAMESPACE}
