# this is the common part for "webots" and "gazebo" simulations
# always run it like that:
# docker compose -f compose.sim.yaml -f compose.sim.gazebo.yaml up
# or
# docker compose -f compose.sim.yaml -f compose.sim.webots.yaml up

services:

  rviz:
    image: husarion/rviz2:humble-11.2.9-20240111
    runtime: ${DOCKER_RUNTIME:-runc}
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
      - NVIDIA_VISIBLE_DEVICES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
      - NVIDIA_DRIVER_CAPABILITIES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz

  navigation:
    image: husarion/navigation2:humble-1.1.12-20240123
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    command: >
      ros2 launch nav2_bringup bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=True
