x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env
  environment:
    - CYCLONEDDS_URI=file:///lan-cyclonedds.xml

services:

  rosbot-xl:
    image: husarion/rosbot-xl:humble-0.8.2-20230712
    <<: *net-config
    volumes:
    - ./config/lan-cyclonedds.xml:/lan-cyclonedds.xml
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-True}

  microros:
    image: husarion/micro-ros-agent:humble-3.1.3-20231013-stable
    <<: *net-config
    command: ros2 run micro_ros_agent micro_ros_agent  udp4 --port 8888

  rplidar:
    image: husarion/rplidar:humble
    <<: *net-config
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    volumes:
    - ./config/lan-cyclonedds.xml:/lan-cyclonedds.xml
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  slam:
    image: husarion/navigation2:humble-1.1.8-20230809
    <<: *net-config
    depends_on:
      rplidar: { condition: service_healthy }
    volumes:
      - ./config/${SLAM_MODE:-slam}_params.yaml:/params.yaml
      - ./maps:/maps
      - ./config/lan-cyclonedds.xml:/lan-cyclonedds.xml
    environment:
      - SLAM_MODE=${SLAM_MODE:-slam}
      - CYCLONEDDS_URI=file:///lan-cyclonedds.xml
    command: >
      ros2 launch nav2_bringup ${SLAM_MODE:-slam}_launch.py
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=False

  navigation:
    image: husarion/navigation2:humble-1.1.8-20230809
    <<: *net-config
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./config/lan-cyclonedds.xml:/lan-cyclonedds.xml
    command: >
      ros2 launch nav2_bringup navigation_launch.py
        params_file:=/params.yaml
        use_sim_time:=False;
