x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:

  rosbot-xl:
    image: husarion/rosbot-xl:humble-0.8.2-20230712
    <<: *net-config
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-True}

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    <<: *net-config
    command: MicroXRCEAgent udp4 --port 8888

  rplidar:
    image: husarion/rplidar:humble
    <<: *net-config
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  navigation:
    image: husarion/navigation2:humble-arm64-from-sourece
    <<: *net-config
    depends_on:
      rplidar: { condition: service_healthy }
      rosbot-xl: { condition: service_healthy }
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    command: >
      ros2 launch nav2_bringup bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=False
