x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:


  slam:
    image: husarion/navigation2:humble-1.1.8-20230809
    <<: *net-config
    volumes:
      - ./config/${SLAM_MODE:-slam}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SLAM_MODE=${SLAM_MODE:-slam}
    command: >
      ros2 launch nav2_bringup ${SLAM_MODE:-slam}_launch.py
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=False

